# Site
repository: radcli14/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eliott Radcliffe
title: Mechanical Engineer and Dynamics Expert, with a Record of Success in Leadership and Staff Development
email: eliott.radcliffe@dc-engineer.com
website: https://www.dc-engineer.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  radcli14
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: radcli14
linkedin_username: eliott-radcliffe-dcdc-llc
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: mobilemultibodydynamics
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Seeking opportunities in an entrepreneurial or startup environment, where I will apply over a decade of mechanical and aerospace engineering experience, alongside a unique software application development skillset.
  I am passionate about simulation and analysis of moving mechanical systems, and 3-D design and visualization on novel platforms, including mobile devices.

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Michigan State University
        caption: 2008 - 2010
        sub_title: M.S. Mechanical Engineering 
        quote: >
          Performed aeroacoustics research leading to a journal publication and patent
        description: | # this will include new lines to allow paragraphs
          , and the thesis "Development of an Optical Feedback-Controlled Microphone for Aeroacoustics Research"

        #  I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DCDC LLC
        link: https://dc-engineer.com
        link_text: DC-Engineer.com
        sub_title: District of Columbia | Dynamics & Control | Design & Code | Data Analytics & Consulting
        caption: November 2017 - Present
        quote: >
          A bag of tricks from a scientific box
        description: | # this will include new lines to allow paragraphs
          I founded an independent software development company, creating education-grade engineering applications, focused on mobile platforms to be inclusive of students and professionals at all budgets. 
          We also provide mechanical, aerospace, and software engineering services and consulting.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
