# Site
repository: radcli14/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eliott Radcliffe
title: Mechanical engineer, dynamics expert, and mobile application developer, with a history of success in leadership and staff development
email: eliott.radcliffe@dc-engineer.com
website: https://www.dc-engineer.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  radcli14
instagram_username: radcli14
linkedin_username: eliott-radcliffe-dcdc-llc
youtube_username: mobilemultibodydynamics

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/puppyMobileSiteLinkImage.jpg
about_content: | # this will include new lines to allow paragraphs
  I have over a decade of industry experience at a university affiliated research center providing expertise on large-scale aerospace projects.
  For the past year, I have begun a transition into a career focused on software development, with a passion for simulation and analysis of moving mechanical systems, and 3-D design and visualization on novel platforms, including mobile and augmented reality devices.
  Currently, I am seeking consulting, contracting, or freelance opportunities in an entrepreneurial or startup environment, where I can leverage my unique multidisciplinary skillsets in mechanical and software fields.

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Michigan State University
        caption: 2004 - 2010
        sub_title: B.S and M.S. Mechanical Engineering 
        quote: >
          Thesis titled "Development of an Optical Feedback-Controlled Microphone for Aeroacoustics Research"

  - title: Technical Skills and Miscellaneous
    layout: text
    content: | # this will include new lines to allow paragraphs
       * __Programming:__ Python, Swift, Kotlin, C#, MATLAB, Mathematica, LabVIEW
       * __Analysis:__ NumPy, SciPy, SymPy, Pandas, matplotlib, TensorFlow
       * __App Development:__ SwiftUI, Jetpack Compose, Kotlin Multiplatform
       * __3-D Rendering:__ Unity, SceneKit, RealityKit, Google Filament, Three.js
       * __Computer Aided Engineering:__ Abaqus, Simulink, Simscape Multibody, SIMPACK
       * __Office/Typesetting:__ Microsoft Office, LaTeX
       * __Awards:__ NASA GSRP Fellowship (2008, 2009), Aegis Ballistic Missile Defense Excellence Award (2018)
       * __Security Clearance:__ SECRET, active from 2010-2023

  - title: Entrepreneurial Experience
    layout: list
    content:
      - layout: left
        title: DCDC LLC
        link: https://dc-engineer.com
        link_text: DC-Engineer.com
        sub_title: District of Columbia | Dynamics & Control | Design & Code | Data Analytics & Consulting
        caption: December 2023 - Present
        quote: >
          Founder and independent software developer
        description: | # this will include new lines to allow paragraphs # I founded an independent software development company, creating education-grade engineering applications, focused on mobile platforms to be inclusive of students and professionals at all budgets. # We also provide mechanical, aerospace, and software engineering services and consulting.
          * Providing mechanical, aerospace, and software engineering services
          * Wrote code in Swift, Kotlin, and Python for multi-platform deployment
          * Applied the machine learning framework TensorFlow to the estimation of aerodynamic properties of race cars
          * Released applications on the [App Store](https://apps.apple.com/us/developer/eliott-radcliffe/id1477487767) and [Google Play](https://play.google.com/store/apps/dev?id=8234827172371467507)
          * Published Python notebooks on the simulation and visualization of mechanical systems, see: [Double Pendulum](https://www.dc-engineer.com/double-pendulum/)

      - layout: top-middle
        title: MOMDYN
        sub_title: Mobile Multibody Dynamics
        link: https://www.dc-engineer.com/mobile-multibody-dynamics/
        link_text: Official Website
        additional_links:
          - title: Download on the App Store
            icon: fab fa-app-store-ios
            url: https://apps.apple.com/us/app/mobile-multibody-dynamics/id1491149780
          - title: MOMDYN on YouTube
            icon: fab fa-youtube
            url: https://www.youtube.com/channel/UC7ij1ezmh8a3Q7N3gF4zUkQ
          - title: Documentation
            icon: fab fa-info
            url: https://momdyn.github.io/html/index.html
        quote: >
          The first multibody dynamics app for iOS and Android
        description: | # this will include new lines to allow paragraphs
          MOMDYN provides a native UI that is familiar to engineers and physicists who have studied classical mechanics, with a powerful set of features similar to modern modeling and simulation software. 
          A Python-based numerical equation generation and solving engine provides the scientific backbone for native iOS and Android applications written in Swift and Kotlin.

      - layout: top-middle
        title: Juego de la Rana
        link: https://www.dc-engineer.com/juego-de-la-rana/
        link_text: Official Website
        additional_links:
          - title: Download on the App Store
            icon: fab fa-app-store-ios
            url: https://apps.apple.com/us/app/juego-de-la-rana/id6680199511
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/radcli14/larana
          - title: Making of video on YouTube
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=vuecTw81q-k&t=5s
        quote: >
          An augmented reality (AR) version of the Basque tavern game
        description: | # this will include new lines to allow paragraphs
          La Rana is an adaptation of the real-world game where one attempts to toss a coin into the mouth of a brass frog statue.
          The iOS game is created using the RealityKit framework, with 3D models created using Blender and photogrammetry.

      - layout: top-middle
        title: YouKon
        link: https://www.dc-engineer.com/youkon/
        link_text: Official Website
        additional_links:
          - title: GitHub
            icon: fab fa-github
            url: https://github.com/radcli14/youkon
          - title: Material properties video on YouTube
            icon: fab fa-youtube
            url: https://www.youtube.com/watch?v=83AwR-pyuDk&t=10s
        quote: >
          A unit converter designed for engineers
        description: | # this will include new lines to allow paragraphs
          YouKon provides a convenient interface to create databases of engineering properties, and simultaneous conversion to a consistent unit system.
          The application is created in Jetpack Compose Multiplatform for deployment to iOS and Android from a single code base.

  - title: Industry Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: JHU/APL
        sub_title: The Johns Hopkins University Applied Physics Laboratory
        caption: 2010 - 2023
        quote: > 
          Over a decade of experience as a mechanical engineer in the aerospace industry
        description: |
          **Dynamics Section Supervisor in the Aerospace and Mechanical Engineering Group (2017-2023)**

            * Managed 7 professional staff with advanced engineering degrees and research expertise
            * Navigated the COVID-19 pandemic with zero furloughs, layoffs, or resignations
            * Pursued new business opportunities by building relationships with program management and sponsors
            * Coached staff members through the definition and achievement of their personal career objectives

          **Lead Engineer (2015-2016, 2020-2023)**

            * Led hardware sustainment & reliability, trajectory simulation, and hardware-in-the-loop teams
            * Briefed results of APL analyses to government and industry teams
            * Authored documentation describing functionality of critical hardware subsystems   

          **Subject Matter Expert in Structural Dynamics, System Identification, and Propulsion Test & Evaluation**

            * Developed modal analysis and digital signal processing algorithms in MATLAB and Python
            * Created flexible airframe dynamics simulation models using finite element modeling and multibody dynamics software, including Abaqus and SimScape Multibody
            <!--* Supported conceptualization, manufacturing, and integration of test equipment-->
            * Championed aeroelasticity modeling as a core competency and growth area for the dynamics section
  
      - layout: left
        title: MSU FPaCL
        sub_title: Michigan State University Flow Physics and Control Laboratory
        caption: 2008 - 2010
        quote: > 
          Performed aeroacoustics research leading to a journal publication and patent
        description: |
          **Graduate Research Assistant**

           * Developed a feedback-controlled, self-calibrating microphone prototype for aeroacoustics research
           * Implemented control system design techniques and evaluated optical displacement sensor technologies
           * Published results in a peer reviewed journal article and received a US patent

      - layout: left
        title: NASA LaRC
        sub_title: NASA Langley Research Center
        caption: 2008 - 2010
        quote: > 
          Received a prestigious Graduate Student Research Program (GSRP) fellowship
        description: |
          **GSRP Summer Intern**

            * Set up a laboratory test to replicate facility used at MSU for validation of microphone prototype concepts
            * Collaborated with NASA experts in the fields of acoustical measurement and digital signal processing
            * Presented findings to branch and GSRP peer groups

  - title: Publications
    layout: text
    content: |
      **Journal Article**
        * E.J. Radcliffe, A.M. Naguib, W.M. Humphreys, _“A Novel Design of a Feedback-Controlled Optical Microphone for Aeroacoustics Research,”_ Measurement Science and Technology, 21, 105208 (2010), [https://iopscience.iop.org/article/10.1088/0957-0233/21/10/105208](https://iopscience.iop.org/article/10.1088/0957-0233/21/10/105208)
   
      **Patent**
        * E.J. Radcliffe, A.M. Naguib, W.M. Humphreys, _“Acoustic Beam Forming Array Using Feedback-Controlled Microphones for Tuning and Self-Matching of Frequency Response,”_ US Patent 8,848,942, 30 September 2014, [https://ntrs.nasa.gov/api/citations/20150003428/downloads/20150003428.pdf](https://ntrs.nasa.gov/api/citations/20150003428/downloads/20150003428.pdf)
      
      **Conference Proceedings**
        * E.J. Radcliffe, D.P. Seker, E.Y. Chen, N.N. Horne, J.L. Hill, _"Determination of a Predictive Model for Print Quality of Desktop 3D Printers While at Sea,"_ ASME International Design Engineering Technical Conference, Boston, MA, IDETC-CIE-112599, 20 August 2023, [https://doi.org/10.1115/DETC2023-112599](https://doi.org/10.1115/DETC2023-112599)
        * J.T. Melcher, E.J. Radcliffe, C.S. Butler, B.M. Wheaton, _“Effects of Aeroelasticity on Flight Dynamics in the Boundary Layer Transition (BOLT) Experiment,”_ AIAA Aviation Forum, Chicago, IL, 29 June 2022, [https://arc.aiaa.org/doi/abs/10.2514/6.2022-3748](https://arc.aiaa.org/doi/abs/10.2514/6.2022-3748)
        * B.J. Olson, E.J. Radcliffe, R.J. Monroe, B.J. Vidmar, and R.A. Caldwell Jr., _“An Inverse Force Identification Methodology for High-fidelity Dynamic Thrust Measurements of Guided Interceptor Missile Divert and Attitude Control Systems,”_ 17th U.S. National Congress on Theoretical & Applied Mechanics (East Lansing, Michigan), Abstract D-10-402, 2014
        * R.N. Couch, E.J. Radcliffe, B.J. Olson, R.A. Caldwell Jr., and B.F. Feeny, _“Modal Parameter Identification of a Missile Launcher Structure for Finite Element Model Correlation,”_ 17th U.S. National Congress on Theoretical & Applied Mechanics (East Lansing, Michigan), Abstract D-10-1180, 2014
        * E.J. Radcliffe, A.M. Naguib, W.M. Humphreys, _“Design and Characterization of an Optical Feedback Controlled Microphone for Aeroacoustics Research,”_ 62nd Annual Meeting of the APS Division of Fluid Dynamics, 54 (9), Minneapolis, MN. Nov. 22-24 (2009)
 
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
